
CREATE OR REPLACE PROCEDURE MAIN_DRIVER()
    RETURNS STRING
    LANGUAGE SQL
AS
    BEGIN
        CALL OUR_FIRST_DB.PUBLIC.MAIN_DATASETUP();
        CALL OUR_FIRST_DB.PUBLIC.TRANSFORM_ORDER_DATA();
        CALL COMPUTE_ORDER_VALUE_BY_PRIORITY();
        
        -- Save the data to putput tables
        CREATE OR REPLACE TABLE TRANSFORMED_ORDER_DATA AS SELECT * FROM OUR_FIRST_DB.PUBLIC.TRANSFORMED_ORDERS;
        CREATE OR REPLACE TABLE AGG_ORDER_VALUE_BY_PRIORITY AS SELECT * FROM OUR_FIRST_DB.PUBLIC.ORDER_VALUE_BY_PRIORITY;
    END;