-- Sets up a temporary table from having the test data - for the test cases. 


CREATE OR REPLACE PROCEDURE TESTCASE_1_DATASETUP()
    RETURNS STRING
    LANGUAGE SQL
AS
    BEGIN        
        CREATE OR REPLACE TEMPORARY TABLE OUR_FIRST_DB.PUBLIC.RAW_ORDERS AS 
        (SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS WHERE O_ORDERDATE>to_date('01-01-1998', 'MM-DD-YYYY')); 
    END;