
CREATE OR REPLACE PROCEDURE TEST_DRIVER()
    RETURNS STRING
    LANGUAGE SQL
AS
    BEGIN
        CREATE TABLE IF NOT EXISTS OUR_FIRST_DB.PUBLIC.UNIT_TEST_RESULTS (TEST_FUNCTION STRING, TEST_NAME STRING, RUNTIME TIMESTAMP, STATUS STRING);
        CALL OUR_FIRST_DB.PUBLIC.TESTCASE_1_DATASETUP();
        CALL OUR_FIRST_DB.PUBLIC.TRANSFORM_ORDER_DATA_TEST();
        CALL OUR_FIRST_DB.PUBLIC.ORDER_VALUE_BY_PRIORITY_TEST();        
    END;
    
CALL TEST_DRIVER();
SELECT * FROM OUR_FIRST_DB.PUBLIC.UNIT_TEST_RESULTS;


