-- Databricks notebook source
CREATE OR REPLACE TEMP VIEW STATION_DATA AS
SELECT NAME, STATION, SUBSTR(STATION, 0, 3) AS STATION_TYPE, DATE, MONTH(DATE) AS MONTH,
CASE
    WHEN ELEVATION <=100 THEN 1
    WHEN ELEVATION >100 AND ELEVATION <=200 THEN 1
    WHEN ELEVATION >200 AND ELEVATION <=300 THEN 3
    WHEN ELEVATION >300 AND ELEVATION <=400 THEN 4
    WHEN ELEVATION >400 AND ELEVATION <=500 THEN 5
    WHEN ELEVATION >500 THEN 6
END AS ELEVATION_GRADE,
CASE 
    WHEN LATITUDE <=24 THEN 'TROPICAL'
    WHEN LATITUDE >24 AND LATITUDE <=30 THEN 1
    WHEN LATITUDE >30 AND LATITUDE <=35 THEN 2
    WHEN LATITUDE >35 AND LATITUDE <=40 THEN 3
    WHEN LATITUDE >40 AND LATITUDE <=45 THEN 4
    WHEN LATITUDE >45 AND LATITUDE <=50 THEN 5
END AS LATITUDE_ZONE,
CASE
    WHEN UNIT = 'F' THEN ROUND (TAVG * 1.0, 1)
    WHEN UNIT = 'C' THEN ROUND( ((TAVG * 1.8) + 32), 1)
    ELSE 9999
END AS AVG_TEMP_F,
CASE
    WHEN UNIT = 'C' THEN ROUND (TAVG *1.0, 1)
    WHEN UNIT = 'F' THEN ROUND( ((TAVG - 32) * 0.5555), 1)
    ELSE 9999
END AS AVG_TEMP_C
FROM RAW_STATION_DATA